# Generated by Django 6.0 on 2026-01-07 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_num', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid contact number (10–15 digits)', regex='^\\+?\\d{10,15}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('admission_date', models.DateField()),
                ('course', models.CharField(max_length=50)),
                ('course_description', models.TextField()),
            ],
        ),
    ]
